config/routes.rb
Rails.application.routes.draw do
  resources :affiliations
  resources :locations
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  require 'csv'
  has_many :people
  def self.import
    table = CSV.parse(File.read('data/csv_sheet1.csv'), headers: true)
    loc = table.by_col[4]
    loc.each do |row|
      if !row.nil?
        self.find_or_create_by!(
          name: row
        )
      end
    end
  end
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  before_action :set_affiliation, only: [:show, :edit, :update, :destroy]

  # GET /affiliations
  # GET /affiliations.json
  def index
    @affiliations = Affiliation.all
  end

  # GET /affiliations/1
  # GET /affiliations/1.json
  def show
  end

  # GET /affiliations/new
  def new
    @affiliation = Affiliation.new
  end

  # GET /affiliations/1/edit
  def edit
  end

  # POST /affiliations
  # POST /affiliations.json
  def create
    @affiliation = Affiliation.new(affiliation_params)

    respond_to do |format|
      if @affiliation.save
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully created.' }
        format.json { render :show, status: :created, location: @affiliation }
      else
        format.html { render :new }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliations/1
  # PATCH/PUT /affiliations/1.json
  def update
    respond_to do |format|
      if @affiliation.update(affiliation_params)
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully updated.' }
        format.json { render :show, status: :ok, location: @affiliation }
      else
        format.html { render :edit }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliations/1
  # DELETE /affiliations/1.json
  def destroy
    @affiliation.destroy
    respond_to do |format|
      format.html { redirect_to affiliations_url, notice: 'Affiliation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affiliation_params
      params.require(:affiliation).permit(:name)
    end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/_form.html.erb
<%= form_with(model: affiliation, local: true) do |form| %>
  <% if affiliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affiliation.errors.count, "error") %> prohibited this affiliation from being saved:</h2>

      <ul>
        <% affiliation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/affiliations/edit.html.erb
<h1>Editing Affiliation</h1>

<%= render 'form', affiliation: @affiliation %>

<%= link_to 'Show', @affiliation %> |
<%= link_to 'Back', affiliations_path %>

app/views/affiliations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Affiliations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @affiliations.each do |affiliation| %>
      <tr>
        <td><%= affiliation.name %></td>
        <td><%= link_to 'Show', affiliation %></td>
        <td><%= link_to 'Edit', edit_affiliation_path(affiliation) %></td>
        <td><%= link_to 'Destroy', affiliation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Affiliation', new_affiliation_path %>

app/views/affiliations/new.html.erb
<h1>New Affiliation</h1>

<%= render 'form', affiliation: @affiliation %>

<%= link_to 'Back', affiliations_path %>

app/views/affiliations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @affiliation.name %>
</p>

<%= link_to 'Edit', edit_affiliation_path(@affiliation) %> |
<%= link_to 'Back', affiliations_path %>